ALTER TABLE allocations
ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN added_by VARCHAR(255),
ADD COLUMN added_date DATETIME DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN modified_by VARCHAR(255),
ADD COLUMN modified_date DATETIME DEFAULT CURRENT_TIMESTAMP; 